from __future__ import annotations

from pathlib import Path

from ssh_manage.models import ManagedEntry
from ssh_manage.util import ensure_private_dir, validate_alias


MANAGED_DIR = Path.home() / ".ssh" / "ssh-manage"
CONFIG_PATH = MANAGED_DIR / "config"
KEYS_DIR = MANAGED_DIR / "keys"
SSH_CONFIG_PATH = Path.home() / ".ssh" / "config"
AGENT_SOCKET = Path.home() / ".ssh" / "proton-pass-agent.sock"
INCLUDE_LINE = "Include ~/.ssh/ssh-manage/config"


def write_managed_config(
    entries: list[ManagedEntry],
    *,
    ssh_config_path: Path = SSH_CONFIG_PATH,
    managed_config_path: Path = CONFIG_PATH,
    keys_dir: Path = KEYS_DIR,
    agent_socket: Path = AGENT_SOCKET,
) -> None:
    ensure_private_dir(ssh_config_path.parent)
    ensure_private_dir(managed_config_path.parent)
    ensure_private_dir(keys_dir)
    ensure_include(ssh_config_path)

    blocks: list[str] = [
        "# Generated by ssh-manage. Do not edit by hand.",
        "",
    ]
    for entry in sorted(entries, key=lambda item: item.alias):
        validate_alias(entry.alias)
        key_path = keys_dir / f"{entry.alias}.pub"
        key_path.write_text(_with_newline(entry.public_key), encoding="utf-8")
        key_path.chmod(0o600)
        blocks.append(_host_block(entry, key_path=key_path, agent_socket=agent_socket))

    managed_config_path.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")
    managed_config_path.chmod(0o600)


def ensure_include(ssh_config_path: Path = SSH_CONFIG_PATH) -> None:
    if ssh_config_path.exists():
        content = ssh_config_path.read_text(encoding="utf-8")
    else:
        content = ""
    lines = content.splitlines()
    if any(line.strip() == INCLUDE_LINE for line in lines):
        ssh_config_path.chmod(0o600)
        return
    prefix = INCLUDE_LINE + "\n"
    new_content = prefix + ("\n" + content if content else "")
    ssh_config_path.write_text(new_content, encoding="utf-8")
    ssh_config_path.chmod(0o600)


def _host_block(entry: ManagedEntry, *, key_path: Path, agent_socket: Path) -> str:
    return "\n".join(
        [
            f"Host {entry.alias}",
            f"    HostName {entry.host}",
            f"    User {entry.user}",
            f"    Port {entry.port}",
            f"    IdentityAgent {agent_socket}",
            f"    IdentityFile {key_path}",
            "    IdentitiesOnly yes",
            "",
        ]
    )


def _with_newline(value: str) -> str:
    return value if value.endswith("\n") else value + "\n"
